swagger: '2.0'
info:
  title: test
  description: No description
  version: v1
schemes:
  - https
paths:
  '/get/{pathvar}/{anotherVar}':
    get:
      summary: 'FFF-44564:test'
      description: Add your description here
      parameters:
        - in: header
          name: Authorization
          required: true
          type: string
        - in: path
          name: pathvar
          type: string
          required: true
        - in: path
          name: anotherVar
          type: string
          required: true
        - in: query
          name: hola
          type: string
          required: true
      responses: &ref_0
        '200':
          description: OK
  '/newmethod/{id}/idtype/{idtype}':
    post:
      summary: 'hlkjh:5642-GetNewRecipe'
      description: Add your description here
      parameters:
        - in: body
          name: variable1
          schema:
            type: object
            properties:
              variable1:
                type: string
          required: true
        - in: path
          name: id
          type: string
          required: true
        - in: path
          name: idtype
          type: string
          required: true
        - in: query
          name: quer
          type: string
          required: true
      responses: *ref_0
